default_platform(:ios)

platform :ios do
  desc "Build e upload su TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true
    )

    gym(
      workspace: "bemyrider.xcworkspace",
      scheme: "bemyrider",
      configuration: "Release",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='#{ENV["PROVISIONING_PROFILE_NAME"]}' DEVELOPMENT_TEAM=79K6W58FPR",
      export_options: {
        provisioningProfiles: {
          "com.app.bemyrider" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      },
      output_directory: "./build",
      output_name: "bemyrider.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
