default_platform(:ios)

platform :ios do
  desc "Build e upload su TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")
    )

    gym(
      workspace: "bemyrider.xcworkspace",
      scheme: "bemyrider",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.app.bemyrider" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      },
      output_directory: "./build",
      output_name: "bemyrider.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
